# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('descrition', models.CharField(blank=True, max_length=500, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_freq', models.CharField(blank=True, max_length=20, null=True)),
                ('ram', models.CharField(blank=True, max_length=20, null=True)),
                ('hdd', models.CharField(blank=True, max_length=20, null=True)),
                ('display', models.CharField(blank=True, max_length=10, null=True)),
                ('videocard', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('dvd', models.BooleanField(default=False)),
                ('lte', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=True)),
                ('wifi', models.BooleanField(default=True)),
                ('price', models.FloatField(default=0)),
                ('image', models.FilePathField(blank=True, null=True)),
            ],
        ),
    ]
