# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
